version: "3.7"
services:
  slow-bar:
    build:
      context: bar-service
    environment:
      SPRING_APPLICATION_NAME: slowbar
      SLEEP: 2001
      SPRING_KAFKA_CONSUMER_GROUP-ID: slow
  faster-bar:
    build:
      context: bar-service
    environment:
      SPRING_APPLICATION_NAME: fastbar
      SLEEP: 2000
      SPRING_KAFKA_CONSUMER_GROUP-ID: fast
  foo:
    build:
      context: foo-service
    ports:
      - 5402:8080
  kafka:
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      KAFKA_ADVERTISED_HOST_PORT: kafka:9092
    image: trajano/kafka
